CREATE TABLE ARTIKLI(
    SIFRA SERIAL PRIMARY KEY NOT NULL,
    NAZIV VARCHAR (20) NOT NULL,
	KOLICINA INTEGER NOT NULL,
	CENA FLOAT NOT NULL
);

INSERT INTO ARTIKLI(NAZIV,KOLICINA,CENA) VALUES ('Cokolada',500,99.990);
INSERT INTO ARTIKLI(NAZIV,KOLICINA,CENA) VALUES ('mleko',300,89.99);
INSERT INTO ARTIKLI(NAZIV,KOLICINA,CENA) VALUES ('jogurt',100,105);
INSERT INTO ARTIKLI(NAZIV,KOLICINA,CENA) VALUES ('kackavalj',100,300);
INSERT INTO ARTIKLI(NAZIV,KOLICINA,CENA) VALUES ('sladoled',150,110);
INSERT INTO ARTIKLI(NAZIV,KOLICINA,CENA) VALUES ('sok',300,80);
INSERT INTO ARTIKLI(NAZIV,KOLICINA,CENA) VALUES ('jaja',400,100);
INSERT INTO ARTIKLI(NAZIV,KOLICINA,CENA) VALUES ('zvake',50,60);
INSERT INTO ARTIKLI(NAZIV,KOLICINA,CENA) VALUES ('bombone',10,80);
INSERT INTO ARTIKLI(NAZIV,KOLICINA,CENA) VALUES ('krem',20,480);
INSERT INTO ARTIKLI(NAZIV,KOLICINA,CENA) VALUES ('hleb',50,50)

SELECT * FROM ARTIKLI 
