SELECT * FROM RADNICI;

INSERT INTO RADNICI (IME_PREZIME,POZICIJA,PLATA) VALUES ('Ognjen SIMIC', 'Majstor',80000);
INSERT INTO RADNICI (IME_PREZIME,POZICIJA,PLATA) VALUES ('Nikola Nikolic', 'Majstor',80000);
INSERT INTO RADNICI (IME_PREZIME,POZICIJA,PLATA) VALUES ('Iva krstic', 'Segert',80000);
INSERT INTO RADNICI (IME_PREZIME,POZICIJA,PLATA) VALUES ('Dusan Carapic', 'Segert',80000);
INSERT INTO RADNICI (IME_PREZIME,POZICIJA,PLATA) VALUES ('Angelina Prpic', 'Dekorator',80000);
INSERT INTO RADNICI (IME_PREZIME,POZICIJA,PLATA) VALUES ('Marjana LEKSIC', 'Cistacica',80000);
INSERT INTO RADNICI (IME_PREZIME,POZICIJA,PLATA) VALUES ('Petar Maglic', 'Marketing',80000);
INSERT INTO RADNICI (IME_PREZIME,POZICIJA,PLATA) VALUES ('Goran Amidzic', 'Prodavac',80000);
INSERT INTO RADNICI (IME_PREZIME,POZICIJA,PLATA) VALUES ('Tamara Kropic', 'Asistenkinja',80000);